include: package:dart_flutter_team_lints/analysis_options.yaml


analyzer:
  language:
    strict-casts: false
  errors:
    avoid_dynamic_calls: ignore

linter:
  rules:
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - package_api_docs
    - test_types_in_equals
